# Generated by Django 5.2.6 on 2025-09-22 01:23

from django.contrib.postgres.operations import CreateExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        CreateExtension('postgis'),
        CreateExtension('postgis_topology'),
        CreateExtension('fuzzystrmatch'),
        CreateExtension('postgis_tiger_geocoder'),
    ]