version: "3.9"

services:
  db:
    image: postgis/postgis:16-3.5
    restart: always
    shm_size: 128mb
    container_name: django-places-db
    environment:
      POSTGRES_DB: postgis
      POSTGRES_USER: django_places
      POSTGRES_PASSWORD: django_places
    ports:
      - 5434:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
